// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSr0AwduLi3nF9IqGvEMw3t9Zpgi4V0M4',
    appId: '1:647942447613:web:e636696efbe2f8eff9f994',
    messagingSenderId: '647942447613',
    projectId: 'project-1-d2d61',
    authDomain: 'project-1-d2d61.firebaseapp.com',
    databaseURL: 'https://project-1-d2d61-default-rtdb.firebaseio.com',
    storageBucket: 'project-1-d2d61.firebasestorage.app',
    measurementId: 'G-MTL400F47E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMWawM4jX-hhnaDn0MczmV-uLXFgLyEtI',
    appId: '1:647942447613:android:44266436f2bc70adf9f994',
    messagingSenderId: '647942447613',
    projectId: 'project-1-d2d61',
    databaseURL: 'https://project-1-d2d61-default-rtdb.firebaseio.com',
    storageBucket: 'project-1-d2d61.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhQWYLCTR8H8NbNGvlQTXh7S_ERsnim30',
    appId: '1:647942447613:ios:8d80e88c3007ae9af9f994',
    messagingSenderId: '647942447613',
    projectId: 'project-1-d2d61',
    databaseURL: 'https://project-1-d2d61-default-rtdb.firebaseio.com',
    storageBucket: 'project-1-d2d61.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhQWYLCTR8H8NbNGvlQTXh7S_ERsnim30',
    appId: '1:647942447613:ios:8d80e88c3007ae9af9f994',
    messagingSenderId: '647942447613',
    projectId: 'project-1-d2d61',
    databaseURL: 'https://project-1-d2d61-default-rtdb.firebaseio.com',
    storageBucket: 'project-1-d2d61.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSr0AwduLi3nF9IqGvEMw3t9Zpgi4V0M4',
    appId: '1:647942447613:web:4212716f0c1d424ff9f994',
    messagingSenderId: '647942447613',
    projectId: 'project-1-d2d61',
    authDomain: 'project-1-d2d61.firebaseapp.com',
    databaseURL: 'https://project-1-d2d61-default-rtdb.firebaseio.com',
    storageBucket: 'project-1-d2d61.firebasestorage.app',
    measurementId: 'G-WYWL1RFGQX',
  );
}
